--- #YAML:1.0
 name: Apache2::WebApp::Toolkit
 abstract: A simplified web application framework
 version: 0.03
 author:
   - Marc S. Brooks <mbrooks@cpan.org>
 license: perl and artistic
 distribution_type: module
 requires:
   Apache2::Request: 0
   AppConfig: 0
   Template: 0
   Params::Validate: 0
 build_requires:
   Apache::Test: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20
