--- #YAML:1.0
name: Apache2::WebApp::Toolkit
abstract: Simplified web application framework
version: 0.36
author:
  - Marc S. Brooks <mbrooks@cpan.org>
license: perl and artistic
distribution_type: module
requires:
  Apache2::Request: 0
  AppConfig: 0
  Template: 0
  File::Copy::Recursive: 0
  Params::Validate: 0
build_requires:
  Apache::Test: 0
  Test::More: 0
no_index:
  directory:
    - example
    - usr
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
