# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-WebApp-Toolkit
version:      0.07
version_from: lib/Apache2/WebApp.pm
installdirs:  site
requires:
    Apache2::Request:              0
    Apache::Test:                  0
    AppConfig:                     0
    Params::Validate:              0
    Template:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
